# Generated by Django 5.2.13 on 2026-05-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0002_alter_inquirysession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquirysession",
            name="invalid_response_count",
            field=models.PositiveIntegerField(
                default=0, help_text="유효하지 않은 답변 반복 횟수"
            ),
        ),
        migrations.AddField(
            model_name="inquirysession",
            name="is_extended",
            field=models.BooleanField(default=False, help_text="질의 연장 여부"),
        ),
        migrations.AddField(
            model_name="inquirysession",
            name="max_turns",
            field=models.PositiveIntegerField(
                default=5, help_text="기본 질의 제한 횟수"
            ),
        ),
        migrations.AddField(
            model_name="inquirysession",
            name="turn_count",
            field=models.PositiveIntegerField(default=0, help_text="현재 질의 횟수"),
        ),
        migrations.AlterField(
            model_name="inquirysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "진행 중"),
                    ("AWAITING_EXTENSION_APPROVAL", "연장 승인 대기 중"),
                    ("COMPLETED", "완료"),
                    ("FAILED_LIMIT_REACHED", "질의 제한 도달"),
                ],
                default="IN_PROGRESS",
                help_text="세션 상태",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RootCause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="도출된 근본 원인 내용")),
                (
                    "confidence_score",
                    models.FloatField(help_text="분석 확신도 점수 (0.0 ~ 1.0)"),
                ),
                (
                    "confidence_label",
                    models.CharField(
                        help_text="사용자 노출용 확신도 라벨", max_length=20
                    ),
                ),
                (
                    "can_detail",
                    models.BooleanField(default=False, help_text="상세화 가능 여부"),
                ),
                (
                    "detailing_guide",
                    models.TextField(
                        blank=True,
                        help_text="상세화가 가능할 경우의 분석 방향 가이드",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="분석 결과 생성 시각"
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        help_text="연결된 진단 세션",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_cause",
                        to="inquiry.inquirysession",
                    ),
                ),
            ],
        ),
    ]
